version: '3.8'

services:
  mtls-server:
    build:
      context: ./MtlsServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./certificates:/app/certificates:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080
    networks:
      - mtls-network

  mtls-client:
    build:
      context: ./MtlsClient
      dockerfile: Dockerfile
    depends_on:
      - mtls-server
    volumes:
      - ./certificates:/app/certificates:ro
    networks:
      - mtls-network
    command: ["sh", "-c", "sleep 10 && dotnet MtlsClient.dll"]

networks:
  mtls-network:
    driver: bridge